# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainInterface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 800))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.TabView = QtWidgets.QTabWidget(self.centralwidget)
        self.TabView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.TabView.sizePolicy().hasHeightForWidth())
        self.TabView.setSizePolicy(sizePolicy)
        self.TabView.setMinimumSize(QtCore.QSize(800, 600))
        self.TabView.setToolTipDuration(-1)
        self.TabView.setTabPosition(QtWidgets.QTabWidget.North)
        self.TabView.setTabBarAutoHide(False)
        self.TabView.setObjectName("TabView")
        self.RawDataTab = QtWidgets.QWidget()
        self.RawDataTab.setObjectName("RawDataTab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.RawDataTab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.RawDataTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.rawDataTable = QtWidgets.QTableWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(80)
        sizePolicy.setHeightForWidth(self.rawDataTable.sizePolicy().hasHeightForWidth())
        self.rawDataTable.setSizePolicy(sizePolicy)
        self.rawDataTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.rawDataTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.rawDataTable.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.rawDataTable.setObjectName("rawDataTable")
        self.rawDataTable.setColumnCount(0)
        self.rawDataTable.setRowCount(0)
        self.rawDataTable.horizontalHeader().setDefaultSectionSize(80)
        self.verticalLayout_6.addWidget(self.rawDataTable)
        self.widget_8 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_6 = QtWidgets.QWidget(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setObjectName("widget_6")
        self.RawData_BYTES_NUM_Text = QtWidgets.QPlainTextEdit(self.widget_6)
        self.RawData_BYTES_NUM_Text.setGeometry(QtCore.QRect(120, 20, 104, 31))
        self.RawData_BYTES_NUM_Text.setReadOnly(True)
        self.RawData_BYTES_NUM_Text.setObjectName("RawData_BYTES_NUM_Text")
        self.label_6 = QtWidgets.QLabel(self.widget_6)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 111, 16))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.widget_6)
        self.widget_7 = QtWidgets.QWidget(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setObjectName("widget_7")
        self.label_7 = QtWidgets.QLabel(self.widget_7)
        self.label_7.setGeometry(QtCore.QRect(10, 30, 131, 16))
        self.label_7.setObjectName("label_7")
        self.RawData_GOTO_Text = QtWidgets.QLineEdit(self.widget_7)
        self.RawData_GOTO_Text.setGeometry(QtCore.QRect(140, 20, 113, 31))
        self.RawData_GOTO_Text.setObjectName("RawData_GOTO_Text")
        self.horizontalLayout_5.addWidget(self.widget_7)
        self.verticalLayout_6.addWidget(self.widget_8)
        self.horizontalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.RawDataTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.RawData_BIN_Text = QtWidgets.QPlainTextEdit(self.widget_3)
        self.RawData_BIN_Text.setGeometry(QtCore.QRect(80, 30, 104, 31))
        self.RawData_BIN_Text.setReadOnly(True)
        self.RawData_BIN_Text.setObjectName("RawData_BIN_Text")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 60, 16))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.RawData_DEC_Text = QtWidgets.QPlainTextEdit(self.widget_4)
        self.RawData_DEC_Text.setGeometry(QtCore.QRect(80, 30, 104, 31))
        self.RawData_DEC_Text.setReadOnly(True)
        self.RawData_DEC_Text.setObjectName("RawData_DEC_Text")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 60, 16))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setObjectName("widget_5")
        self.RawData_ASCII_Text = QtWidgets.QPlainTextEdit(self.widget_5)
        self.RawData_ASCII_Text.setGeometry(QtCore.QRect(80, 30, 104, 31))
        self.RawData_ASCII_Text.setReadOnly(True)
        self.RawData_ASCII_Text.setObjectName("RawData_ASCII_Text")
        self.label_5 = QtWidgets.QLabel(self.widget_5)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 60, 16))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.widget_5)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.TabView.addTab(self.RawDataTab, "")
        self.PacketsTab = QtWidgets.QWidget()
        self.PacketsTab.setToolTipDuration(3)
        self.PacketsTab.setObjectName("PacketsTab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.PacketsTab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_20 = QtWidgets.QWidget(self.PacketsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_20.sizePolicy().hasHeightForWidth())
        self.widget_20.setSizePolicy(sizePolicy)
        self.widget_20.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_20.setObjectName("widget_20")
        self.label_20 = QtWidgets.QLabel(self.widget_20)
        self.label_20.setGeometry(QtCore.QRect(30, 10, 91, 16))
        self.label_20.setObjectName("label_20")
        self.comboBox_parser_list = QtWidgets.QComboBox(self.widget_20)
        self.comboBox_parser_list.setGeometry(QtCore.QRect(120, 10, 221, 26))
        self.comboBox_parser_list.setObjectName("comboBox_parser_list")
        self.label_21 = QtWidgets.QLabel(self.widget_20)
        self.label_21.setGeometry(QtCore.QRect(410, 10, 121, 16))
        self.label_21.setObjectName("label_21")
        self.lineEdit_number_of_packets = QtWidgets.QLineEdit(self.widget_20)
        self.lineEdit_number_of_packets.setGeometry(QtCore.QRect(540, 10, 161, 21))
        self.lineEdit_number_of_packets.setReadOnly(True)
        self.lineEdit_number_of_packets.setObjectName("lineEdit_number_of_packets")
        self.verticalLayout_9.addWidget(self.widget_20)
        self.listWidget_packets = QtWidgets.QListWidget(self.PacketsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.listWidget_packets.sizePolicy().hasHeightForWidth())
        self.listWidget_packets.setSizePolicy(sizePolicy)
        self.listWidget_packets.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidget_packets.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listWidget_packets.setObjectName("listWidget_packets")
        self.verticalLayout_9.addWidget(self.listWidget_packets)
        self.TabView.addTab(self.PacketsTab, "")
        self.ParsedDataTab = QtWidgets.QWidget()
        self.ParsedDataTab.setObjectName("ParsedDataTab")
        self.TabView.addTab(self.ParsedDataTab, "")
        self.GraphTab = QtWidgets.QWidget()
        self.GraphTab.setObjectName("GraphTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.GraphTab)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.matplotView = QtWidgets.QWidget(self.GraphTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.matplotView.sizePolicy().hasHeightForWidth())
        self.matplotView.setSizePolicy(sizePolicy)
        self.matplotView.setMinimumSize(QtCore.QSize(500, 300))
        self.matplotView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.matplotView.setToolTipDuration(4)
        self.matplotView.setObjectName("matplotView")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.matplotView)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget_graph = QtWidgets.QTableWidget(self.matplotView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_graph.sizePolicy().hasHeightForWidth())
        self.tableWidget_graph.setSizePolicy(sizePolicy)
        self.tableWidget_graph.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tableWidget_graph.setColumnCount(7)
        self.tableWidget_graph.setObjectName("tableWidget_graph")
        self.tableWidget_graph.setRowCount(0)
        self.tableWidget_graph.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.tableWidget_graph)
        self.graph = QtWidgets.QWidget(self.matplotView)
        self.graph.setObjectName("graph")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.graph)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3.addWidget(self.graph)
        self.horizontalLayout.addWidget(self.matplotView)
        self.rightView = QtWidgets.QWidget(self.GraphTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.rightView.sizePolicy().hasHeightForWidth())
        self.rightView.setSizePolicy(sizePolicy)
        self.rightView.setObjectName("rightView")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.rightView)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout.addWidget(self.rightView)
        self.TabView.addTab(self.GraphTab, "")
        self.CalibrationTab = QtWidgets.QWidget()
        self.CalibrationTab.setObjectName("CalibrationTab")
        self.TabView.addTab(self.CalibrationTab, "")
        self.StreamTab = QtWidgets.QWidget()
        self.StreamTab.setEnabled(True)
        self.StreamTab.setObjectName("StreamTab")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.StreamTab)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_9 = QtWidgets.QWidget(self.StreamTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.StreamTabWidget = QtWidgets.QTabWidget(self.widget_9)
        self.StreamTabWidget.setObjectName("StreamTabWidget")
        self.FileTab = QtWidgets.QWidget()
        self.FileTab.setObjectName("FileTab")
        self.widget_19 = QtWidgets.QWidget(self.FileTab)
        self.widget_19.setGeometry(QtCore.QRect(150, 160, 471, 361))
        self.widget_19.setObjectName("widget_19")
        self.lineEdit_file_path = QtWidgets.QLineEdit(self.widget_19)
        self.lineEdit_file_path.setGeometry(QtCore.QRect(110, 40, 321, 21))
        self.lineEdit_file_path.setObjectName("lineEdit_file_path")
        self.label_19 = QtWidgets.QLabel(self.widget_19)
        self.label_19.setGeometry(QtCore.QRect(30, 40, 60, 16))
        self.label_19.setObjectName("label_19")
        self.pushButton_browse_files = QtWidgets.QPushButton(self.widget_19)
        self.pushButton_browse_files.setGeometry(QtCore.QRect(20, 70, 113, 32))
        self.pushButton_browse_files.setObjectName("pushButton_browse_files")
        self.StreamTabWidget.addTab(self.FileTab, "")
        self.SerialTab = QtWidgets.QWidget()
        self.SerialTab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SerialTab.setObjectName("SerialTab")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.SerialTab)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_12 = QtWidgets.QWidget(self.SerialTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_12.sizePolicy().hasHeightForWidth())
        self.widget_12.setSizePolicy(sizePolicy)
        self.widget_12.setMinimumSize(QtCore.QSize(400, 0))
        self.widget_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_13 = QtWidgets.QWidget(self.widget_12)
        self.widget_13.setMinimumSize(QtCore.QSize(400, 0))
        self.widget_13.setMaximumSize(QtCore.QSize(600, 50))
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.widget_13)
        self.label_9.setMinimumSize(QtCore.QSize(50, 0))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.comboBox_serial_baud_rate = QtWidgets.QComboBox(self.widget_13)
        self.comboBox_serial_baud_rate.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_serial_baud_rate.setObjectName("comboBox_serial_baud_rate")
        self.comboBox_serial_baud_rate.addItem("")
        self.comboBox_serial_baud_rate.addItem("")
        self.comboBox_serial_baud_rate.addItem("")
        self.comboBox_serial_baud_rate.addItem("")
        self.comboBox_serial_baud_rate.addItem("")
        self.comboBox_serial_baud_rate.addItem("")
        self.comboBox_serial_baud_rate.addItem("")
        self.comboBox_serial_baud_rate.addItem("")
        self.comboBox_serial_baud_rate.addItem("")
        self.comboBox_serial_baud_rate.addItem("")
        self.comboBox_serial_baud_rate.addItem("")
        self.comboBox_serial_baud_rate.addItem("")
        self.comboBox_serial_baud_rate.addItem("")
        self.comboBox_serial_baud_rate.addItem("")
        self.comboBox_serial_baud_rate.addItem("")
        self.comboBox_serial_baud_rate.addItem("")
        self.comboBox_serial_baud_rate.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox_serial_baud_rate)
        self.verticalLayout_8.addWidget(self.widget_13)
        self.widget_14 = QtWidgets.QWidget(self.widget_12)
        self.widget_14.setMinimumSize(QtCore.QSize(400, 0))
        self.widget_14.setMaximumSize(QtCore.QSize(600, 50))
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_14 = QtWidgets.QLabel(self.widget_14)
        self.label_14.setMinimumSize(QtCore.QSize(50, 0))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        self.comboBox_serial_byte_size = QtWidgets.QComboBox(self.widget_14)
        self.comboBox_serial_byte_size.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_serial_byte_size.setObjectName("comboBox_serial_byte_size")
        self.comboBox_serial_byte_size.addItem("")
        self.comboBox_serial_byte_size.addItem("")
        self.comboBox_serial_byte_size.addItem("")
        self.comboBox_serial_byte_size.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox_serial_byte_size)
        self.verticalLayout_8.addWidget(self.widget_14)
        self.widget_15 = QtWidgets.QWidget(self.widget_12)
        self.widget_15.setMinimumSize(QtCore.QSize(400, 0))
        self.widget_15.setMaximumSize(QtCore.QSize(600, 50))
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_15 = QtWidgets.QLabel(self.widget_15)
        self.label_15.setMinimumSize(QtCore.QSize(50, 0))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_12.addWidget(self.label_15)
        self.comboBox_serial_parity = QtWidgets.QComboBox(self.widget_15)
        self.comboBox_serial_parity.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_serial_parity.setObjectName("comboBox_serial_parity")
        self.comboBox_serial_parity.addItem("")
        self.comboBox_serial_parity.addItem("")
        self.comboBox_serial_parity.addItem("")
        self.comboBox_serial_parity.addItem("")
        self.comboBox_serial_parity.addItem("")
        self.horizontalLayout_12.addWidget(self.comboBox_serial_parity)
        self.verticalLayout_8.addWidget(self.widget_15)
        self.widget_16 = QtWidgets.QWidget(self.widget_12)
        self.widget_16.setMinimumSize(QtCore.QSize(400, 0))
        self.widget_16.setMaximumSize(QtCore.QSize(600, 50))
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_16 = QtWidgets.QLabel(self.widget_16)
        self.label_16.setMinimumSize(QtCore.QSize(50, 0))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_13.addWidget(self.label_16)
        self.comboBox_serial_stop_bits = QtWidgets.QComboBox(self.widget_16)
        self.comboBox_serial_stop_bits.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_serial_stop_bits.setObjectName("comboBox_serial_stop_bits")
        self.comboBox_serial_stop_bits.addItem("")
        self.comboBox_serial_stop_bits.addItem("")
        self.comboBox_serial_stop_bits.addItem("")
        self.horizontalLayout_13.addWidget(self.comboBox_serial_stop_bits)
        self.verticalLayout_8.addWidget(self.widget_16)
        self.widget_17 = QtWidgets.QWidget(self.widget_12)
        self.widget_17.setMinimumSize(QtCore.QSize(400, 0))
        self.widget_17.setMaximumSize(QtCore.QSize(600, 50))
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_17 = QtWidgets.QLabel(self.widget_17)
        self.label_17.setMinimumSize(QtCore.QSize(50, 0))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_14.addWidget(self.label_17)
        self.lineEdit_serial_timeout = QtWidgets.QLineEdit(self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_serial_timeout.sizePolicy().hasHeightForWidth())
        self.lineEdit_serial_timeout.setSizePolicy(sizePolicy)
        self.lineEdit_serial_timeout.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_serial_timeout.setObjectName("lineEdit_serial_timeout")
        self.horizontalLayout_14.addWidget(self.lineEdit_serial_timeout)
        self.verticalLayout_8.addWidget(self.widget_17)
        self.checkBox_serial_xonxoff = QtWidgets.QCheckBox(self.widget_12)
        self.checkBox_serial_xonxoff.setObjectName("checkBox_serial_xonxoff")
        self.verticalLayout_8.addWidget(self.checkBox_serial_xonxoff)
        self.checkBox_serial_rtsdts = QtWidgets.QCheckBox(self.widget_12)
        self.checkBox_serial_rtsdts.setObjectName("checkBox_serial_rtsdts")
        self.verticalLayout_8.addWidget(self.checkBox_serial_rtsdts)
        self.checkBox_serial_dtrdsr = QtWidgets.QCheckBox(self.widget_12)
        self.checkBox_serial_dtrdsr.setObjectName("checkBox_serial_dtrdsr")
        self.verticalLayout_8.addWidget(self.checkBox_serial_dtrdsr)
        self.widget_18 = QtWidgets.QWidget(self.widget_12)
        self.widget_18.setMinimumSize(QtCore.QSize(400, 0))
        self.widget_18.setMaximumSize(QtCore.QSize(600, 50))
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_18)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_18 = QtWidgets.QLabel(self.widget_18)
        self.label_18.setMinimumSize(QtCore.QSize(50, 0))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_15.addWidget(self.label_18)
        self.comboBox_serial_ports = QtWidgets.QComboBox(self.widget_18)
        self.comboBox_serial_ports.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_serial_ports.setObjectName("comboBox_serial_ports")
        self.horizontalLayout_15.addWidget(self.comboBox_serial_ports)
        self.verticalLayout_8.addWidget(self.widget_18)
        self.checkBox_manual_port = QtWidgets.QCheckBox(self.widget_12)
        self.checkBox_manual_port.setObjectName("checkBox_manual_port")
        self.verticalLayout_8.addWidget(self.checkBox_manual_port)
        self.lineEdit_manual_port = QtWidgets.QLineEdit(self.widget_12)
        self.lineEdit_manual_port.setEnabled(False)
        self.lineEdit_manual_port.setObjectName("lineEdit_manual_port")
        self.verticalLayout_8.addWidget(self.lineEdit_manual_port)
        self.horizontalLayout_9.addWidget(self.widget_12, 0, QtCore.Qt.AlignHCenter)
        self.StreamTabWidget.addTab(self.SerialTab, "")
        self.ServerTab = QtWidgets.QWidget()
        self.ServerTab.setObjectName("ServerTab")
        self.StreamTabWidget.addTab(self.ServerTab, "")
        self.horizontalLayout_8.addWidget(self.StreamTabWidget)
        self.horizontalLayout_7.addWidget(self.widget_9)
        self.widget_10 = QtWidgets.QWidget(self.StreamTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_11 = QtWidgets.QWidget(self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_11.sizePolicy().hasHeightForWidth())
        self.widget_11.setSizePolicy(sizePolicy)
        self.widget_11.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.widget_11)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.StreamTypeSelection = QtWidgets.QComboBox(self.widget_11)
        self.StreamTypeSelection.setCurrentText("")
        self.StreamTypeSelection.setObjectName("StreamTypeSelection")
        self.verticalLayout_4.addWidget(self.StreamTypeSelection)
        self.verticalLayout_7.addWidget(self.widget_11)
        self.StartStopStreamButton = QtWidgets.QPushButton(self.widget_10)
        self.StartStopStreamButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.StartStopStreamButton.sizePolicy().hasHeightForWidth())
        self.StartStopStreamButton.setSizePolicy(sizePolicy)
        self.StartStopStreamButton.setCheckable(True)
        self.StartStopStreamButton.setObjectName("StartStopStreamButton")
        self.verticalLayout_7.addWidget(self.StartStopStreamButton)
        self.pushButton_Load_File = QtWidgets.QPushButton(self.widget_10)
        self.pushButton_Load_File.setObjectName("pushButton_Load_File")
        self.verticalLayout_7.addWidget(self.pushButton_Load_File)
        self.pushButton_Clear_Data = QtWidgets.QPushButton(self.widget_10)
        self.pushButton_Clear_Data.setObjectName("pushButton_Clear_Data")
        self.verticalLayout_7.addWidget(self.pushButton_Clear_Data)
        self.horizontalLayout_7.addWidget(self.widget_10)
        self.TabView.addTab(self.StreamTab, "")
        self.horizontalLayout_6.addWidget(self.TabView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 22))
        self.menubar.setObjectName("menubar")
        self.menu_Session = QtWidgets.QMenu(self.menubar)
        self.menu_Session.setToolTipDuration(10)
        self.menu_Session.setObjectName("menu_Session")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose_Testbench = QtWidgets.QAction(MainWindow)
        self.actionClose_Testbench.setObjectName("actionClose_Testbench")
        self.menu_Session.addAction(self.actionClose_Testbench)
        self.menubar.addAction(self.menu_Session.menuAction())

        self.retranslateUi(MainWindow)
        self.TabView.setCurrentIndex(3)
        self.StreamTabWidget.setCurrentIndex(0)
        self.comboBox_serial_baud_rate.setCurrentIndex(12)
        self.comboBox_serial_byte_size.setCurrentIndex(3)
        self.StreamTypeSelection.setCurrentIndex(-1)
        self.actionClose_Testbench.triggered['bool'].connect(MainWindow.close)
        self.checkBox_manual_port.toggled['bool'].connect(self.lineEdit_manual_port.setEnabled)
        self.checkBox_manual_port.toggled['bool'].connect(self.comboBox_serial_ports.setDisabled)
        self.StartStopStreamButton.toggled['bool'].connect(self.pushButton_Clear_Data.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Testbench 0.1"))
        self.label_6.setText(_translate("MainWindow", "Number of Bytes:"))
        self.label_7.setText(_translate("MainWindow", "GoTo Byte Number:"))
        self.label_3.setText(_translate("MainWindow", "BIN:"))
        self.label_4.setText(_translate("MainWindow", "DEC:"))
        self.label_5.setText(_translate("MainWindow", "ASCII:"))
        self.TabView.setTabText(self.TabView.indexOf(self.RawDataTab), _translate("MainWindow", "Raw Data"))
        self.label_20.setText(_translate("MainWindow", "Select Parser:"))
        self.label_21.setText(_translate("MainWindow", "Number of Packets:"))
        self.TabView.setTabText(self.TabView.indexOf(self.PacketsTab), _translate("MainWindow", "Packets"))
        self.TabView.setTabText(self.TabView.indexOf(self.ParsedDataTab), _translate("MainWindow", "Parsed Data"))
        self.TabView.setTabText(self.TabView.indexOf(self.GraphTab), _translate("MainWindow", "Graph"))
        self.TabView.setTabText(self.TabView.indexOf(self.CalibrationTab), _translate("MainWindow", "Calibration"))
        self.lineEdit_file_path.setPlaceholderText(_translate("MainWindow", "enter file path here"))
        self.label_19.setText(_translate("MainWindow", "File Path:"))
        self.pushButton_browse_files.setText(_translate("MainWindow", "Browse Files"))
        self.StreamTabWidget.setTabText(self.StreamTabWidget.indexOf(self.FileTab), _translate("MainWindow", "File"))
        self.label_9.setText(_translate("MainWindow", "Baud Rate:"))
        self.comboBox_serial_baud_rate.setCurrentText(_translate("MainWindow", "9600"))
        self.comboBox_serial_baud_rate.setItemText(0, _translate("MainWindow", "50"))
        self.comboBox_serial_baud_rate.setItemText(1, _translate("MainWindow", "75"))
        self.comboBox_serial_baud_rate.setItemText(2, _translate("MainWindow", "110"))
        self.comboBox_serial_baud_rate.setItemText(3, _translate("MainWindow", "134"))
        self.comboBox_serial_baud_rate.setItemText(4, _translate("MainWindow", "150"))
        self.comboBox_serial_baud_rate.setItemText(5, _translate("MainWindow", "200"))
        self.comboBox_serial_baud_rate.setItemText(6, _translate("MainWindow", "300"))
        self.comboBox_serial_baud_rate.setItemText(7, _translate("MainWindow", "600"))
        self.comboBox_serial_baud_rate.setItemText(8, _translate("MainWindow", "1200"))
        self.comboBox_serial_baud_rate.setItemText(9, _translate("MainWindow", "1800"))
        self.comboBox_serial_baud_rate.setItemText(10, _translate("MainWindow", "2400"))
        self.comboBox_serial_baud_rate.setItemText(11, _translate("MainWindow", "4800"))
        self.comboBox_serial_baud_rate.setItemText(12, _translate("MainWindow", "9600"))
        self.comboBox_serial_baud_rate.setItemText(13, _translate("MainWindow", "18200"))
        self.comboBox_serial_baud_rate.setItemText(14, _translate("MainWindow", "38400"))
        self.comboBox_serial_baud_rate.setItemText(15, _translate("MainWindow", "57600"))
        self.comboBox_serial_baud_rate.setItemText(16, _translate("MainWindow", "115200"))
        self.label_14.setText(_translate("MainWindow", "Byte Size:"))
        self.comboBox_serial_byte_size.setItemText(0, _translate("MainWindow", "FIVEBITS"))
        self.comboBox_serial_byte_size.setItemText(1, _translate("MainWindow", "SIXBITS"))
        self.comboBox_serial_byte_size.setItemText(2, _translate("MainWindow", "SEVENBITS"))
        self.comboBox_serial_byte_size.setItemText(3, _translate("MainWindow", "EIGHTBITS"))
        self.label_15.setText(_translate("MainWindow", "Parity:"))
        self.comboBox_serial_parity.setItemText(0, _translate("MainWindow", "PARITY_NONE"))
        self.comboBox_serial_parity.setItemText(1, _translate("MainWindow", "PARITY_EVEN"))
        self.comboBox_serial_parity.setItemText(2, _translate("MainWindow", "PARITY_ODD"))
        self.comboBox_serial_parity.setItemText(3, _translate("MainWindow", "PARITY_MARK"))
        self.comboBox_serial_parity.setItemText(4, _translate("MainWindow", "PARITY_SPACE"))
        self.label_16.setText(_translate("MainWindow", "Stop Bits:"))
        self.comboBox_serial_stop_bits.setItemText(0, _translate("MainWindow", "STOPBITS_ONE"))
        self.comboBox_serial_stop_bits.setItemText(1, _translate("MainWindow", "STOPBITS_ONE_POINT_FIVE"))
        self.comboBox_serial_stop_bits.setItemText(2, _translate("MainWindow", "STOPBITS_TWO"))
        self.label_17.setText(_translate("MainWindow", "Timeout [s]:"))
        self.lineEdit_serial_timeout.setText(_translate("MainWindow", "0"))
        self.checkBox_serial_xonxoff.setText(_translate("MainWindow", "XON/XOFF"))
        self.checkBox_serial_rtsdts.setText(_translate("MainWindow", "RTS/CTS"))
        self.checkBox_serial_dtrdsr.setText(_translate("MainWindow", "DTR/DSR"))
        self.label_18.setText(_translate("MainWindow", "Port:"))
        self.checkBox_manual_port.setText(_translate("MainWindow", "Manual Port Selection"))
        self.lineEdit_manual_port.setPlaceholderText(_translate("MainWindow", "enter port e.g. /dev/ttyUSB0 or COM3"))
        self.StreamTabWidget.setTabText(self.StreamTabWidget.indexOf(self.SerialTab), _translate("MainWindow", "Serial"))
        self.StreamTabWidget.setTabText(self.StreamTabWidget.indexOf(self.ServerTab), _translate("MainWindow", "HTTPServer"))
        self.label_8.setText(_translate("MainWindow", "Choose Stream Type"))
        self.StartStopStreamButton.setText(_translate("MainWindow", "Start Stream"))
        self.pushButton_Load_File.setText(_translate("MainWindow", "Load File"))
        self.pushButton_Clear_Data.setText(_translate("MainWindow", "Clear Data"))
        self.TabView.setTabText(self.TabView.indexOf(self.StreamTab), _translate("MainWindow", "Stream"))
        self.menu_Session.setTitle(_translate("MainWindow", "&Session"))
        self.actionClose_Testbench.setText(_translate("MainWindow", "Close Testbench"))

