# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainInterface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1290, 729)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1290, 650))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.TabView = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.TabView.sizePolicy().hasHeightForWidth())
        self.TabView.setSizePolicy(sizePolicy)
        self.TabView.setMinimumSize(QtCore.QSize(800, 600))
        self.TabView.setToolTipDuration(-1)
        self.TabView.setTabPosition(QtWidgets.QTabWidget.North)
        self.TabView.setTabBarAutoHide(False)
        self.TabView.setObjectName("TabView")
        self.RawDataTab = QtWidgets.QWidget()
        self.RawDataTab.setObjectName("RawDataTab")
        self.TabView.addTab(self.RawDataTab, "")
        self.PacketsTab = QtWidgets.QWidget()
        self.PacketsTab.setToolTipDuration(3)
        self.PacketsTab.setObjectName("PacketsTab")
        self.TabView.addTab(self.PacketsTab, "")
        self.SentencesTab = QtWidgets.QWidget()
        self.SentencesTab.setObjectName("SentencesTab")
        self.TabView.addTab(self.SentencesTab, "")
        self.GraphTab = QtWidgets.QWidget()
        self.GraphTab.setObjectName("GraphTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.GraphTab)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.matplotView = QtWidgets.QWidget(self.GraphTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.matplotView.sizePolicy().hasHeightForWidth())
        self.matplotView.setSizePolicy(sizePolicy)
        self.matplotView.setMinimumSize(QtCore.QSize(500, 300))
        self.matplotView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.matplotView.setToolTipDuration(4)
        self.matplotView.setObjectName("matplotView")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.matplotView)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.matplotView)
        self.label_2.setMaximumSize(QtCore.QSize(100, 30))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.graph = QtWidgets.QWidget(self.matplotView)
        self.graph.setObjectName("graph")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.graph)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3.addWidget(self.graph)
        self.horizontalLayout.addWidget(self.matplotView)
        self.rightView = QtWidgets.QWidget(self.GraphTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.rightView.sizePolicy().hasHeightForWidth())
        self.rightView.setSizePolicy(sizePolicy)
        self.rightView.setObjectName("rightView")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.rightView)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dataView = QtWidgets.QWidget(self.rightView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dataView.sizePolicy().hasHeightForWidth())
        self.dataView.setSizePolicy(sizePolicy)
        self.dataView.setObjectName("dataView")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.dataView)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.dataView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.verticalHeader().setVisible(False)
        self.horizontalLayout_3.addWidget(self.tableWidget)
        self.toggleBox = QtWidgets.QWidget(self.dataView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggleBox.sizePolicy().hasHeightForWidth())
        self.toggleBox.setSizePolicy(sizePolicy)
        self.toggleBox.setObjectName("toggleBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.toggleBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.toggleBox)
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.pointsCheckBox = QtWidgets.QCheckBox(self.toggleBox)
        self.pointsCheckBox.setObjectName("pointsCheckBox")
        self.verticalLayout_2.addWidget(self.pointsCheckBox)
        self.avrgCheckBox = QtWidgets.QCheckBox(self.toggleBox)
        self.avrgCheckBox.setObjectName("avrgCheckBox")
        self.verticalLayout_2.addWidget(self.avrgCheckBox)
        self.horizontalSlider = QtWidgets.QSlider(self.toggleBox)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_2.addWidget(self.horizontalSlider)
        self.label = QtWidgets.QLabel(self.toggleBox)
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label.setAutoFillBackground(False)
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.comboBox.raise_()
        self.pointsCheckBox.raise_()
        self.horizontalSlider.raise_()
        self.label.raise_()
        self.avrgCheckBox.raise_()
        self.horizontalLayout_3.addWidget(self.toggleBox)
        self.verticalLayout.addWidget(self.dataView)
        self.placeholderView = QtWidgets.QWidget(self.rightView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.placeholderView.sizePolicy().hasHeightForWidth())
        self.placeholderView.setSizePolicy(sizePolicy)
        self.placeholderView.setObjectName("placeholderView")
        self.verticalLayout.addWidget(self.placeholderView)
        self.horizontalLayout.addWidget(self.rightView)
        self.TabView.addTab(self.GraphTab, "")
        self.CalibrationTab = QtWidgets.QWidget()
        self.CalibrationTab.setObjectName("CalibrationTab")
        self.TabView.addTab(self.CalibrationTab, "")
        self.SerialTab = QtWidgets.QWidget()
        self.SerialTab.setObjectName("SerialTab")
        self.TabView.addTab(self.SerialTab, "")
        self.horizontalLayout_2.addWidget(self.TabView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 22))
        self.menubar.setObjectName("menubar")
        self.menu_Session = QtWidgets.QMenu(self.menubar)
        self.menu_Session.setToolTipDuration(10)
        self.menu_Session.setObjectName("menu_Session")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose_Testbench = QtWidgets.QAction(MainWindow)
        self.actionClose_Testbench.setObjectName("actionClose_Testbench")
        self.menu_Session.addAction(self.actionClose_Testbench)
        self.menubar.addAction(self.menu_Session.menuAction())

        self.retranslateUi(MainWindow)
        self.TabView.setCurrentIndex(3)
        self.actionClose_Testbench.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Testbench 0.1"))
        self.TabView.setTabText(self.TabView.indexOf(self.RawDataTab), _translate("MainWindow", "RawData"))
        self.TabView.setTabText(self.TabView.indexOf(self.PacketsTab), _translate("MainWindow", "Packets"))
        self.TabView.setTabText(self.TabView.indexOf(self.SentencesTab), _translate("MainWindow", "Sentences"))
        self.label_2.setText(_translate("MainWindow", "Voltages"))
        self.pointsCheckBox.setText(_translate("MainWindow", "points"))
        self.avrgCheckBox.setText(_translate("MainWindow", "average"))
        self.label.setText(_translate("MainWindow", "0"))
        self.TabView.setTabText(self.TabView.indexOf(self.GraphTab), _translate("MainWindow", "Graph"))
        self.TabView.setTabText(self.TabView.indexOf(self.CalibrationTab), _translate("MainWindow", "Calibration"))
        self.TabView.setTabText(self.TabView.indexOf(self.SerialTab), _translate("MainWindow", "Serial"))
        self.menu_Session.setTitle(_translate("MainWindow", "&Session"))
        self.actionClose_Testbench.setText(_translate("MainWindow", "Close Testbench"))

